// Generated by gencpp from file web_lecture/StringStampList.msg
// DO NOT EDIT!


#ifndef WEB_LECTURE_MESSAGE_STRINGSTAMPLIST_H
#define WEB_LECTURE_MESSAGE_STRINGSTAMPLIST_H

#include <ros/service_traits.h>


#include <web_lecture/StringStampListRequest.h>
#include <web_lecture/StringStampListResponse.h>


namespace web_lecture
{

struct StringStampList
{

typedef StringStampListRequest Request;
typedef StringStampListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringStampList
} // namespace web_lecture


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::web_lecture::StringStampList > {
  static const char* value()
  {
    return "2e57eb5ee95c0a584fb520d98705f88b";
  }

  static const char* value(const ::web_lecture::StringStampList&) { return value(); }
};

template<>
struct DataType< ::web_lecture::StringStampList > {
  static const char* value()
  {
    return "web_lecture/StringStampList";
  }

  static const char* value(const ::web_lecture::StringStampList&) { return value(); }
};


// service_traits::MD5Sum< ::web_lecture::StringStampListRequest> should match
// service_traits::MD5Sum< ::web_lecture::StringStampList >
template<>
struct MD5Sum< ::web_lecture::StringStampListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::web_lecture::StringStampList >::value();
  }
  static const char* value(const ::web_lecture::StringStampListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_lecture::StringStampListRequest> should match
// service_traits::DataType< ::web_lecture::StringStampList >
template<>
struct DataType< ::web_lecture::StringStampListRequest>
{
  static const char* value()
  {
    return DataType< ::web_lecture::StringStampList >::value();
  }
  static const char* value(const ::web_lecture::StringStampListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::web_lecture::StringStampListResponse> should match
// service_traits::MD5Sum< ::web_lecture::StringStampList >
template<>
struct MD5Sum< ::web_lecture::StringStampListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::web_lecture::StringStampList >::value();
  }
  static const char* value(const ::web_lecture::StringStampListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_lecture::StringStampListResponse> should match
// service_traits::DataType< ::web_lecture::StringStampList >
template<>
struct DataType< ::web_lecture::StringStampListResponse>
{
  static const char* value()
  {
    return DataType< ::web_lecture::StringStampList >::value();
  }
  static const char* value(const ::web_lecture::StringStampListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEB_LECTURE_MESSAGE_STRINGSTAMPLIST_H
