// Generated by gencpp from file web_lecture/StringStampListRequest.msg
// DO NOT EDIT!


#ifndef WEB_LECTURE_MESSAGE_STRINGSTAMPLISTREQUEST_H
#define WEB_LECTURE_MESSAGE_STRINGSTAMPLISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace web_lecture
{
template <class ContainerAllocator>
struct StringStampListRequest_
{
  typedef StringStampListRequest_<ContainerAllocator> Type;

  StringStampListRequest_()
    {
    }
  StringStampListRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::web_lecture::StringStampListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_lecture::StringStampListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StringStampListRequest_

typedef ::web_lecture::StringStampListRequest_<std::allocator<void> > StringStampListRequest;

typedef boost::shared_ptr< ::web_lecture::StringStampListRequest > StringStampListRequestPtr;
typedef boost::shared_ptr< ::web_lecture::StringStampListRequest const> StringStampListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_lecture::StringStampListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_lecture::StringStampListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace web_lecture

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::web_lecture::StringStampListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_lecture::StringStampListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_lecture::StringStampListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_lecture::StringStampListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_lecture::StringStampListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_lecture::StringStampListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_lecture::StringStampListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::web_lecture::StringStampListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::web_lecture::StringStampListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_lecture/StringStampListRequest";
  }

  static const char* value(const ::web_lecture::StringStampListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_lecture::StringStampListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::web_lecture::StringStampListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_lecture::StringStampListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringStampListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_lecture::StringStampListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::web_lecture::StringStampListRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WEB_LECTURE_MESSAGE_STRINGSTAMPLISTREQUEST_H
